@{
    Copyright='(c) 2011 - 2019 Przemyslaw Klys. All rights reserved.'
    PrivateData=@{
        PSData=@{
            Tags='HTML',
                'WWW',
                'JavaScript',
                'CSS',
                'Reports',
                'Reporting',
                'Windows',
                'MacOS',
                'Linux'
            ProjectUri='https://github.com/EvotecIT/PSWriteHTML'
            IconUri='https://evotec.xyz/wp-content/uploads/2018/12/PSWriteHTML.png'
            Prerelease=''
        }
    }
    CompatiblePSEditions='Desktop',
        'Core'
    PowerShellVersion='5.1'
    FunctionsToExport='Get-FeaturesInUse',
        'Get-Resources',
        'New-HTML',
        'New-HTMLAnchor',
        'New-HTMLAnchorLink',
        'New-HTMLAnchorName',
        'New-HTMLChart',
        'New-HTMLChartDataSet',
        'New-HTMLCodeBlock',
        'New-HTMLContent',
        'New-HTMLHeading',
        'New-HTMLHorizontalLine',
        'New-HTMLImage',
        'New-HTMLLogo',
        'New-HTMLMessage',
        'New-HTMLPanel',
        'New-HTMLResourceCSS',
        'New-HTMLResourceJS',
        'New-HTMLStatus',
        'New-HTMLStatusItem',
        'New-HTMLTab',
        'New-HTMLTabHead',
        'New-HTMLTable',
        'New-HTMLTag',
        'New-HTMLTimeline',
        'New-HTMLTimelineItem',
        'New-HTMLToast',
        'Save-HTML',
        'Get-HTMLBarChart',
        'Get-HTMLBarChartObject',
        'Get-HTMLLineChart',
        'Get-HTMLLineChartObject',
        'Get-HTMLPieChart',
        'Get-HTMLPieChartObject',
        'Get-HTMLStackedChart',
        'Get-HTMLStackedChartObject'
    Author='Przemyslaw Klys'
    RequiredModules='PSSharedGoods'
    GUID='a7bdf640-f5cb-4acf-9de0-365b322d245c'
    RootModule='PSWriteHTML.psm1'
    AliasesToExport='New-HTMLColumn',
        'New-ResourceCSS',
        'New-CSS',
        'New-ResourceJS',
        'New-JavaScript'
    Description='Module that allows creating HTML content/reports in easy way.'
    ModuleVersion='0.0.13'
    CompanyName='Evotec'
}
