Function New-HTML {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)][ValidateNotNull()][ScriptBlock] $HtmlData = $(Throw "Have you put the open curly brace on the next line?"),
        [switch] $UseCssLinks,
        [switch] $UseStyleLinks,
        [String] $TitleText,
        [String] $CSSPath,
        [String] $CSSName = "default",
        [String] $ScriptPath,
        [String] $ColorSchemePath,
        [String] $LogoPath,
        [string] $LeftLogoName = "Sample",
        [string] $RightLogoName = "Alternate",
        [string] $LeftLogoString,
        [string] $RightLogoString,
        [switch] $HideLogos,
        [switch] $HideTitle,
        [switch] $NoScript,
        [string] $PrimaryColorHex,
        [switch] $AddAuthor,
        [string] $Author,
        [switch] $HideDate,
        [string] $DateFormat = 'yyyy-MM-dd HH:mm:ss',
        [String] $FooterText
    )

    [string] $CurrentDate = (Get-Date).ToString($DateFormat)

    $Options = New-HTMLReportOptions `
        -RightLogoName $RightLogoName `
        -LeftLogoName LeftLogoName  `
        -LeftLogoString $LeftLogoString `
        -RightLogoString $RightLogoString `
        -CSSName $CSSName `
        -CSSPath $CSSPath `
        -ScriptPath $ScriptPath `
        -ColorSchemePath $ColorSchemePath `
        -UseCssLinks:$UseCssLinks `
        -UseStyleLinks:$UseStyleLinks

    $Script:HTMLSchema = @{
        TabsHeaders = [System.Collections.Generic.List[Object]]::new()
        Tabs        = [System.Collections.Generic.List[Object]]::new()
        TabsCurrent = @{}
    }

    '<!DOCTYPE html>'
    New-HTMLTag -Tag 'html' {
        '<!-- HEADER -->'
        New-HTMLTag -Tag 'head' {
            New-HTMLTag -Tag 'meta' -Attributes @{ charset = "utf-8" } -SelfClosing
            New-HTMLTag -Tag 'meta' -Attributes @{ name = 'viewport'; content = 'width=device-width, initial-scale=1' } -SelfClosing

            if (-not $HideTitle) {
                New-HTMLTag -Tag 'title' { $TitleText }
            }
            if ($AddAuthor) {
                if ([String]::IsNullOrWhiteSpace($Author)) { $Author = $env:USERNAME }
                
                "<!--- This page was autogenerated $CurrentDate By $Author -->"
            }

            "<!-- STYLES -->"
            $Options.StyleContent
            '<!-- END STYLES -->'
            '<!-- SCRIPTS -->'
            $Options.ScriptContent
            '<!-- END SCRIPTS -->'


            Add-HTMLHead `
                -Options $Options `
                -UseStyleLinks:$UseStyleLinks `
                -UseCssLinks:$UseCssLinks `
                -TitleText $TitleText `
                -AddAuthor:$AddAuthor `
                -HideTitle:$HideTitle
        }
        '<!-- END HEADER -->'
        '<!-- BODY -->'
        #'<body onload="hide();">'       
        New-HTMLTag -Tag 'body' {
            Add-HTMLBodyOpening -Options $Options -TitleText $TitleText -HideLogos:$HideLogos -HideTitle:$HideTitle -HideDate:$HideDate -PrimaryColorHex $PrimaryColorHex -CurrentDate $CurrentDate       
            Invoke-Command -ScriptBlock $HtmlData
            
            '<!-- FOOTER -->'
            New-HTMLTag -Tag 'footer' { 
                New-HTMLTag -Tag 'div' -Attributes @{ class = 'defaultFooter' } {
                    if ($null -ne $FooterText) {
                        $FooterText = "Copyright &#169; $([DateTime]::Now.Year). All Rights Reserved."
                    }
                    $FooterText
                }
                <#
                New-HTMLTag -Tag 'style' -Attributes @{ id = 'datatables_crazyfix' } {
                    @'                    
                    .tab-content .tab-pane {
                        visibility: hidden;
                        display: block;
                    }
'@
                }
                #>
                "<!-- SCRIPT -->"
                New-HTMLResourceJS {

                    @'   
                    // INIT CODE - simple page-wide initialization based on css selectors
                    // - highlight all pre + code tags (CSS3 selectors)
                    // - use javascript as default language
                    // - use theme "enlighter" as default theme
                    // - replace tabs with 2 spaces
                    EnlighterJS.init("pre", "code", {
                            language: "powershell",
                            theme: "enlighter",
                            indent: 2
                        });
'@

                }
                <#
                New-HTMLResourceJS {
                    @'
                    jQuery(function($) {
                            $("#datatables_crazyfix").remove();
                        });
'@
                }
                #>
                <#
                New-HTMLResourceJS {
                    @'
                    tabButtons.map(function (button) {
                        button.addEventListener("click", function () {
                          document
                            .querySelector("li a.active.button")
                            .classList.remove("active");
                          button.classList.add("active");
                      
                          document
                            .querySelector(".tab-pane.active")
                            .classList.remove("active");
                          document
                            .querySelector(button.getAttribute("href"))
                            .classList.add("active");
                      
                      
                          /****  ADDED RESPONSIVE.RECALC  ****/
                          $(button.getAttribute("href"))
                            .find("table.display.compact")
                            .DataTable().responsive.recalc();
                        })
                      })                   
'@
                }
                #>
                '<!-- END SCRIPTS -->'
            }
            '<!-- END FOOTER -->'
        }
        '<!-- END BODY -->'
    }     
}