Function New-HTML {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)][ValidateNotNull()][ScriptBlock] $HtmlData = $(Throw "Have you put the open curly brace on the next line?"),
        [switch] $UseCssLinks,
        [switch] $UseStyleLinks,
        [String] $TitleText,
        [String] $CSSPath,
        [String] $CSSName = "default",
        [String] $ScriptPath,
        [String] $ColorSchemePath,
        [String] $LogoPath,
        [string] $LeftLogoName = "Sample",
        [string] $RightLogoName = "Alternate",
        [string] $LeftLogoString,
        [string] $RightLogoString,
        [switch] $HideLogos,
        [switch] $NoScript,
        [string] $PrimaryColorHex,
        [switch] $AddAuthor,
        [string] $Author,
        [string] $DateFormat = 'yyyy-MM-dd HH:mm:ss'
    )

    [string] $CurrentDate = (Get-Date).ToString($DateFormat)

    $Options = New-HTMLReportOptions `
        -RightLogoName $RightLogoName `
        -LeftLogoName LeftLogoName  `
        -LeftLogoString $LeftLogoString `
        -RightLogoString $RightLogoString `
        -CSSName $CSSName `
        -CSSPath $CSSPath `
        -ScriptPath $ScriptPath `
        -ColorSchemePath $ColorSchemePath `
        -UseCssLinks:$UseCssLinks `
        -UseStyleLinks:$UseStyleLinks

    $Script:HTMLSchema = @{
        TabsHeaders = @()
    }

    '<!DOCTYPE html>'
    New-HTMLTag -Tag 'html' {
        '<!-- HEADER -->'
        New-HTMLTag -Tag 'head' {
            New-HTMLTag -Tag 'meta' -Attributes @{ charset = "utf-8" } -SelfClosing
            New-HTMLTag -Tag 'meta' -Attributes @{ name = 'viewport'; content = 'width=device-width, initial-scale=1' } -SelfClosing
            New-HTMLTag -Tag 'title' { $TitleText }
            
            if ($AddAuthor) {
                if ([String]::IsNullOrWhiteSpace($Author)) { $Author = $env:USERNAME }
                
                "<!--- This page was autogenerated $CurrentDate By $Author -->"
            }

            "<!-- STYLES -->"       
            $Options.StyleContent
            #New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\timeline.css" -ResourceComment 'Timeline'
            #New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\timeline-ygc.css" -ResourceComment 'Timeline YGC'
            #New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\timeline-scrible.css" -ResourceComment 'Timeline Scrible'
            New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\timeline-simple.css" -ResourceComment 'Timeline Simple'
            New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\skeleton-tabs.css" -ResourceComment 'Skeleton Tabs'
            New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\status.css" -ResourceComment 'Status Buttonical'
            New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\message.css" -ResourceComment 'Message Notifications'
            New-HTMLResourceCSS -FilePath "$PSScriptRoot\..\Resources\CSS\Styles\toasts.css" -ResourceComment 'Toast Notifications'
            '<!-- END STYLES -->'
            '<!-- SCRIPTS -->'
            $Options.ScriptContent
            '<!-- END SCRIPTS -->'
        }
        '<!-- END HEADER -->'
        '<!-- BODY -->'
        #'<body onload="hide();">'       
        New-HTMLTag -Tag 'body' {
            #Add-HTMLBodyOpening -Options $Options -TitleText $TitleText -HideLogos:$HideLogos -HideTitle:$HideTitle -HideDate:$HideDate -PrimaryColorHex $PrimaryColorHex -CurrentDate $CurrentDate
            
            if ($HideLogos -eq $false) {
                $Leftlogo = $Options.Logos[$LeftLogoName]
                $Rightlogo = $Options.Logos[$RightLogoName]
                $LogoContent = @"
                <table><tbody>
                <tr>
                    <td class="clientlogo"><img src="$Leftlogo" /></td>
                    <td class="MainLogo"><img src="$Rightlogo" /></td>
                </tr>
                </tbody></table>
"@
                $LogoContent
            }         
            #if (-not $HideDate) {
            #    New-HTMLTag -Tag 'div' -Attributes @{ class = 'ReportCreated' } -Value { "Report created on $($CurrentDate)" }
            #}

            <# Not sure what for 
            if (!([string]::IsNullOrEmpty($PrimaryColorHex))) {
                if ($PrimaryColorHex.Length -eq 7) {
                    $HTML = $HTML -replace '#337E94', $PrimaryColorHex
                } else {
                    Write-Warning '$PrimaryColorHex must be 7 characters with hash eg "#337E94"'
                }
            }
            #> 
            Invoke-Command -ScriptBlock $HtmlData
            
            '<!-- FOOTER -->'
            New-HTMLTag -Tag 'footer' { 
                #New-HTMLTag -Tag 'div' -Attributes @{ class = 'defaultFooter' } {
                #    if ($null -ne $FooterText) {
                #        $FooterText = "Copyright &#169; $([DateTime]::Now.Year). All Rights Reserved."
                #    }
                #    $FooterText
                #}               
                New-HTMLResourceJS {

                    @'   
                    // INIT CODE - simple page-wide initialization based on css selectors
                    // - highlight all pre + code tags (CSS3 selectors)
                    // - use javascript as default language
                    // - use theme "enlighter" as default theme
                    // - replace tabs with 2 spaces
                    EnlighterJS.init("pre", "code", {
                            language: "powershell",
                            theme: "enlighter",
                            indent: 2
                        });
'@
                }                
            }
            '<!-- END FOOTER -->'
        }
        '<!-- END BODY -->'
    }     
}