function Add-HTMLHead {
    [CmdletBinding()]
    param(
        [string] $TitleText,
        [switch] $UseStyleLinks,
        [switch] $UseCssLinks,
        [switch] $AddAuthor,
        [switch] $HideTitle,
        $Options
    )
    [string] $CurrentDate = (Get-Date).ToString($DateFormat)

    # Replace PNG / JPG files in Styles
    if ($null -ne $Options.StyleContent) {

        Write-Verbose "Logos: $($Options.Logos.Keys -join ',')"
        foreach ($Logo in $Options.Logos.Keys) {
            $Search = "../images/$Logo.png", "DataTables-1.10.18/images/$Logo.png"
            $Replace = $Options.Logos[$Logo]
            foreach ($S in $Search) {
                Write-Verbose "Logos - replacing $S with binary representation"
                $Options.StyleContent = ($Options.StyleContent).Replace($S, $Replace)
            }
        }
    }

    $HTML = New-GenericList -Type [string]
    $HTML.Add("<!DOCTYPE HTML>")
    if ($AddAuthor) {
        if ([String]::IsNullOrWhiteSpace($Author)) {
            $Author = $env:USERNAME
        }
        $HTML.Add("<!--- This page was autogenerated $CurrentDate By $Author -->")
    }
    $HTML.Add("<html>")
    $HTML.Add('<!-- Header -->')
    $HTML.Add('<head>')
    if (-not $HideTitle) {
        $HTML.Add("<Title>$TitleText</Title>")
    }
    $HTML.Add("<!-- Styles -->")
    $HTML.Add("$($Options.StyleContent)")
    $HTML.Add('<!-- Scripts -->')
    $HTML.Add("$($Options.ScriptContent)")
    $HTML.Add('</head>')
    $HTML.Add('')
    return $HTML
}

function Add-HTMLBodyOpening {
    [CmdletBinding()]
    param(
        $Options,
        [string] $TitleText,
        [switch] $HideTitle,
        [switch] $HideLogos,
        [switch] $HideDate,
        [string] $PrimaryColorHex,
        [string] $CurrentDate
    )
    $HTML = New-GenericList -Type [string]
    $HTML.Add('<!-- Body -->')
    #$HTML.Add('<body onload="hide();">')
    $HTML.Add('<body>')

    if ($HideLogos -eq $false) {
        $Leftlogo = $Options.Logos[$LeftLogoName]
        $Rightlogo = $Options.Logos[$RightLogoName]
        $LogoContent = @"
        <table><tbody>
        <tr>
            <td class="clientlogo"><img src="$Leftlogo" /></td>
            <td class="MainLogo"><img src="$Rightlogo" /></td>
        </tr>
        </tbody></table>
"@
    }

    if (-not $HideTitle) {
        $HTML.Add("<!-- Report Header -->")
        $HTML.Add($LogoContent)
        $HTML.Add("<div class=`"pageTitle`">$TitleText</div>")
        $HTML.Add("<hr />")
    }
    if (-not $HideDate) {
        $HTML.Add("<div class=`"ReportCreated`">Report created on $($CurrentDate)</div>")
    }

    if (!([string]::IsNullOrEmpty($PrimaryColorHex))) {
        if ($PrimaryColorHex.Length -eq 7) {
            $HTML = $HTML -replace '#337E94', $PrimaryColorHex
        } else {
            Write-Warning '$PrimaryColorHex must be 7 characters with hash eg "#337E94"'
        }
    }
    return $HTML
}