function Add-HTMLHead {
    param(
        [string] $TitleText,
        [switch] $UseStyleLinks,
        [switch] $UseCssLinks,
        [switch] $AddAuthor,
        [switch] $HideTitle
    )
    [string] $CurrentDate = (Get-Date).ToString($DateFormat)

    $Options = New-HTMLReportOptions -UseCssLinks:$UseCssLinks -UseStyleLinks:$UseStyleLinks

    $HTML = New-GenericList -Type [string]
    $HTML.Add("<!DOCTYPE HTML>")
    if ($AddAuthor) {
        if ([String]::IsNullOrWhiteSpace($Author)) {
            $Author = $env:USERNAME
        }
        $HTML.Add("<!--- This page was autogenerated $CurrentDate By $Author -->")
    }
    $HTML.Add("<html>")
    $HTML.Add('<!-- Header -->')
    $HTML.Add('<head>')
    if (-not $HideTitle) {
        $HTML.Add("<Title>$TitleText</Title>")
    }
    $HTML.Add("<!-- Styles -->")
    $HTML.Add("$($Options.StyleContent)")
    $HTML.Add('<!-- Scripts -->')
    $HTML.Add("$($Options.ScriptContent)")
    $HTML.Add('</head>')
    $HTML.Add('')
    return $HTML
}