function New-HTMLCustomCSS {
    [CmdletBinding()]
    param(
        [System.Collections.IDictionary] $CSS
    )
    foreach ($Key in $CSS.Keys) {
        "<!-- CSS $Key AUTOGENERATED on DEMAND START -->"
        if ($CSS[$Key]) {
            if ($CSS[$Key] -notlike "*<style *") {
                New-HTMLTag -Tag 'style' -Attributes @{ type = 'text/css' } {
                    $CSS[$Key]
                } -NewLine
            } else {
                $CSS[$Key]
            }
        }
        "<!-- CSS $Key AUTOGENERATED on DEMAND END -->"
    }
}