function New-HTMLCustomCSS {
    [CmdletBinding()]
    param(
        [System.Collections.IDictionary] $CSS,
        [switch] $AddComment
    )

    $Output = foreach ($Key in $CSS.Keys) {
        if ($AddComment) { "<!-- CSS $Key AUTOGENERATED on DEMAND START -->" }
        if ($CSS[$Key]) {
            #if ($CSS[$Key] -notlike "*<style *") {

            $CSS[$Key]

            #} else {
            #    $CSS[$Key]
            #}
        }
        if ($AddComment) { "<!-- CSS $Key AUTOGENERATED on DEMAND END -->" }
    }
    if ($Output) {
        New-HTMLTag -Tag 'style' -Attributes @{ type = 'text/css' } {
            $Output
        } -NewLine
    }
}